name: Cypress browser tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  browser-test:
    name: Cypress browser tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          start: yarn storybook:dev
          wait-on: 'http://localhost:9003'
          wait-on-timeout: 120
